### ISSUE TITLE
Fix hr on FFX

### ISSUE THREAD

**Issue by muan** [robert/ifoundthishelped#1]
I need to do this.
![Screen Shot 2013-04-02 at 00 40 29](https://f.cloud.github.com/assets/1153134/326196/8ec07b72-9b25-11e2-803d-c86b43fb4a33.png)

**Comment by robert** [comment]
Que?

On Tue, Apr 2, 2013 at 12:40 AM, Mu-An Chiou notifications@github.comwrote:

> I need to do this.
> [image: Screen Shot 2013-04-02 at 00 40 29]https://f.cloud.github.com/assets/1153134/326196/8ec07b72-9b25-11e2-803d-c86b43fb4a33.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robert/ifoundthishelped/issues/1
> .

## 

copyin.com - Email for teams
robertheaton.com - Writing for people

**Comment by muan** [comment]
I'm reminding myself I need to fix this, it should look like this:
![Screen Shot 2013-04-02 at 10 30 05](https://f.cloud.github.com/assets/1153134/327525/ef4104b0-9b77-11e2-96d3-a448474173c3.png)

**Comment by robert** [comment]
:::)))<<<333

On Tue, Apr 2, 2013 at 10:30 AM, Mu-An Chiou notifications@github.comwrote:

> I'm reminding myself I need to fix this, it should look like this:
> [image: Screen Shot 2013-04-02 at 10 30 05]https://f.cloud.github.com/assets/1153134/327525/ef4104b0-9b77-11e2-96d3-a448474173c3.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robert/ifoundthishelped/issues/1#issuecomment-15765343
> .

## 

copyin.com - Email for teams
robertheaton.com - Writing for people

**Comment by muan** [comment]
::::)
![images](https://f.cloud.github.com/assets/1153134/327531/4c2491ce-9b78-11e2-8117-ed6aade7692a.jpeg)
